command:
  name: build
  description: 'Build site'
commands:
  # Import configuration
  - command: config_split:import
  # Rebuild caches.
  - command: cache:rebuild
    arguments:
        cache: all
